#
[localhost1_servers]
localhost1 ansible_connection=local
#
[localhost2_servers]
localhost2 ansible_connection=local
#
[chroots]
void_target ansible_connection=community.general.chroot ansible_host=/mnt