---
#
#
#

# Pré-fase, criação do meta-pacote.
- name: "BUILDING"
  hosts: localhost
  gather_facts: false
  roles:
    - build_package
  tags: [building]
#eol

# Fase 1, processo de instalação do sistema.
- name: "Fase (1)"
  hosts: localhost
  gather_facts: true
  roles:
    - 01_during_install
  tags: [fase1]
#eol

# Fase 2, processo de pós-instalação do sistema.
- name: "Fase (2)"
  hosts: void_target
  gather_facts: false
  roles:
    - 02_postaf_install
  tags: [fase1]
#eol
