---
#
#
#

# Pré-fase, criação do meta-pacote.
- name: "BUILDING"
  hosts: localhost1
  gather_facts: false
  roles:
    - build_package
  tags: [building]
#eol

# Fase 1, processo de instalação do sistema.
- name: "Fase (1)"
  hosts: localhost2
  gather_facts: false
  roles:
    - 01_during_install
  tags: [fase1]
#eol
