---
#
#
#

- name: "Fase (1)"
  hosts: localhost
  gather_facts: true
  roles:
    - role: 02_during_install
      vars:
        disk: "{{ disk }}"
        repo: "{{ repo }}"
        arch: "{{ arch }}"
        ne_pkgs: "{{ ne_pkgs }}"
      #eol
    #eol
  #eol
#eol
- name: "Fase (2)"
  hosts: chroots
  roles:
    - 03_postaf_install
  #eol
#eol
